### ISSUE TITLE
Crash @Boici

### ISSUE THREAD

**Issue by cipriancaba** [UatsApp/UatsApp#21]
Signup
Singnin
Click boici
Try to write message

https://www.dropbox.com/s/zfl7nsz08q2aro1/Screenshot%202015-08-03%2008.19.44.png?dl=0

**Comment by paulp9426** [comment]
Thanks for opening this issue.
This will be soon Fiexd.
Regards, Paul.

**Comment by cipriancaba** [comment]
Protip: When you fix in issue, only close it after it is integrated in master.. Achieve this by puttin in the commit message: fixes #21 or closes #21 https://help.github.com/articles/closing-issues-via-commit-messages/
